env:
  node: true
  mocha: true
extends: standard
parserOptions:
  ecmaVersion: 2017
  sourceType: module
plugins:
  - mocha
rules:
  mocha/no-exclusive-tests:
    - error
  no-var:
    - error
  semi:
    - error
    - always
  brace-style:
    - error
    - stroustrup
  curly:
    - error
    - multi-or-nest
